

```{r setup, include=FALSE}

solve_assignment <- function(cost_matrix) {
  n <- nrow(cost_matrix)
  assigned_rows <- rep(FALSE, n)
  assigned_cols <- rep(FALSE, n)
  assignments <- numeric(n)
  
  for (i in 1:n) {
    min_cost <- Inf
    min_col <- NA
    
    for (j in 1:n) {
      if (!assigned_cols[j] && cost_matrix[i, j] < min_cost) {
        min_cost <- cost_matrix[i, j]
        min_col <- j
      }
    }
    
    assignments[i] <- min_col
    assigned_rows[i] <- TRUE
    assigned_cols[min_col] <- TRUE
  }
  
  return(assignments)
}

```

```{r cleaning, include=FALSE}

data <- read.csv("données_centroides_classe-cluster_MNIST.csv")
subdata<-data[, -(1:2)]

cost_matrix <- matrix(0, nrow = 10, ncol = 10)

for (i in 1: 10) {
  for (j in 11: 20) {
    cost_matrix[i,j-10]=sum((subdata[i,] - subdata[j,])^2)
  }
}

```


```{r}

times <- list() 
n_times <- 0

for (n in seq(from = 10, to = 10000, by = 1000)) {
  cost_matrix <- pnorm(matrix(rnorm(n * n), nrow = n, ncol = n))
  timing <- system.time(total_cost <- solve_assignment(cost_matrix))
  n_times <- n_times + 1
  times[[n_times]] <- timing["elapsed"]  
}

```

```{r}

library(ggplot2)

ca_times <- c(0.53,1.44,2.24,3.74,5.47,6.61,7.8,11.22)

x <- c(2010,3010,4010,5010,6010,7010,8010,9010)

data <- data.frame(x = log(x), y = log(ca_times))

ggplot(data, aes(x = x, y = y)) +
  geom_point() + 
  labs(x = "log(nb de clusters/classe)", y = "log (temps)", title = "")

model <- lm(log(ca_times)~log(x))
summary(model)
```

```{r}

library(ggplot2)

ca_times <- c(0,0.04,0.16,0.25,0.5,0.69,1,1.31)

x <- c(10,510,1010,1510,2010,2510,3010,3510)

data <- data.frame(x = x, y = log(ca_times))

ggplot(data, aes(x = x, y = y)) +
  geom_point() + 
  labs(x = "nb de clusters/classe", y = "temps", title = "")
```