---
title: "Untitled"
output: html_document
date: "2024-03-22"
---

#génération de tous les clusters prédits et de toutes classes correspondant aux données : 
```{r cleaning, include=FALSE}

generer_tableau <- function(n, k) {
  tableau <- matrix(sample(1:k, n * 2, replace = TRUE), ncol = 2)
  return(tableau)
}

n <- 400 
k <- 10   

resultat <- generer_tableau(n, k)

cost_matrix <- matrix(0, nrow = k, ncol = k)
```

#calcul de la matrice de coût par une fonction de comptage simple d'occurence cluster/classe :
```{r cleaning, include=FALSE}
for (i in 1:n) {
  cluster <- resultat[i, 1]  
  classe <- resultat[i, 2]   
  cost_matrix[cluster, classe] <- cost_matrix[cluster, classe] + 1
}

# Normaliser la matrice de coût
cost_matrix <- 1 - cost_matrix / n
```


#calcul de la matrice de coût par une distance euclidienne de la différence entre centroïde et moyenne de la classe : 
```{r cleaning, include=FALSE}

data <- read.csv("mean_data.csv")
subdata<-data[, -(1:2)]

cost_matrix <- matrix(0, nrow = 10, ncol = 10)

for (i in 1: 10) {
  for (j in 11: 20) {
    cost_matrix[i,j-10]=sum((subdata[i,] - subdata[j,])^2)
  }
}

```

#génération aléatoire des centroïdes des classes et clusters:

```{r cleaning, include=FALSE}

matrice_gaussienne <- matrix(rnorm(nb_lignes * nb_colonnes), nrow = nb_lignes, ncol = nb_colonnes)

matrice_gaussienne_normalisee <- pnorm(matrice_gaussienne)

```

```{r cleaning, include=FALSE}
# Afficher la matrice de coût
print(cost_matrix)

write.csv(cost_matrix, file = "cout_matrice.csv", row.names = FALSE)

```

